/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UtilisateursRouteImport } from './routes/utilisateurs'
import { Route as StatistiquesRouteImport } from './routes/statistiques'
import { Route as SalairesRouteImport } from './routes/salaires'
import { Route as RapportsFinanciersRouteImport } from './routes/rapports-financiers'
import { Route as RapportsRouteImport } from './routes/rapports'
import { Route as ProfilsContratsRouteImport } from './routes/profils-contrats'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PresencesRouteImport } from './routes/presences'
import { Route as PersonnelRouteImport } from './routes/personnel'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as PaiementsRouteImport } from './routes/paiements'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as MessagerieRouteImport } from './routes/messagerie'
import { Route as FraisScolariteRouteImport } from './routes/frais-scolarite'
import { Route as EvaluationsRouteImport } from './routes/evaluations'
import { Route as ElevesRouteImport } from './routes/eleves'
import { Route as DepensesRouteImport } from './routes/depenses'
import { Route as IndexRouteImport } from './routes/index'

const UtilisateursRoute = UtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistiquesRoute = StatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => rootRouteImport,
} as any)
const SalairesRoute = SalairesRouteImport.update({
  id: '/salaires',
  path: '/salaires',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsFinanciersRoute = RapportsFinanciersRouteImport.update({
  id: '/rapports-financiers',
  path: '/rapports-financiers',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsRoute = RapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilsContratsRoute = ProfilsContratsRouteImport.update({
  id: '/profils-contrats',
  path: '/profils-contrats',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PresencesRoute = PresencesRouteImport.update({
  id: '/presences',
  path: '/presences',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonnelRoute = PersonnelRouteImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementsRoute = PaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagerieRoute = MessagerieRouteImport.update({
  id: '/messagerie',
  path: '/messagerie',
  getParentRoute: () => rootRouteImport,
} as any)
const FraisScolariteRoute = FraisScolariteRouteImport.update({
  id: '/frais-scolarite',
  path: '/frais-scolarite',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationsRoute = EvaluationsRouteImport.update({
  id: '/evaluations',
  path: '/evaluations',
  getParentRoute: () => rootRouteImport,
} as any)
const ElevesRoute = ElevesRouteImport.update({
  id: '/eleves',
  path: '/eleves',
  getParentRoute: () => rootRouteImport,
} as any)
const DepensesRoute = DepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/depenses': typeof DepensesRoute
  '/eleves': typeof ElevesRoute
  '/evaluations': typeof EvaluationsRoute
  '/frais-scolarite': typeof FraisScolariteRoute
  '/messagerie': typeof MessagerieRoute
  '/notes': typeof NotesRoute
  '/paiements': typeof PaiementsRoute
  '/parametres': typeof ParametresRoute
  '/personnel': typeof PersonnelRoute
  '/presences': typeof PresencesRoute
  '/profil': typeof ProfilRoute
  '/profils-contrats': typeof ProfilsContratsRoute
  '/rapports': typeof RapportsRoute
  '/rapports-financiers': typeof RapportsFinanciersRoute
  '/salaires': typeof SalairesRoute
  '/statistiques': typeof StatistiquesRoute
  '/utilisateurs': typeof UtilisateursRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/depenses': typeof DepensesRoute
  '/eleves': typeof ElevesRoute
  '/evaluations': typeof EvaluationsRoute
  '/frais-scolarite': typeof FraisScolariteRoute
  '/messagerie': typeof MessagerieRoute
  '/notes': typeof NotesRoute
  '/paiements': typeof PaiementsRoute
  '/parametres': typeof ParametresRoute
  '/personnel': typeof PersonnelRoute
  '/presences': typeof PresencesRoute
  '/profil': typeof ProfilRoute
  '/profils-contrats': typeof ProfilsContratsRoute
  '/rapports': typeof RapportsRoute
  '/rapports-financiers': typeof RapportsFinanciersRoute
  '/salaires': typeof SalairesRoute
  '/statistiques': typeof StatistiquesRoute
  '/utilisateurs': typeof UtilisateursRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/depenses': typeof DepensesRoute
  '/eleves': typeof ElevesRoute
  '/evaluations': typeof EvaluationsRoute
  '/frais-scolarite': typeof FraisScolariteRoute
  '/messagerie': typeof MessagerieRoute
  '/notes': typeof NotesRoute
  '/paiements': typeof PaiementsRoute
  '/parametres': typeof ParametresRoute
  '/personnel': typeof PersonnelRoute
  '/presences': typeof PresencesRoute
  '/profil': typeof ProfilRoute
  '/profils-contrats': typeof ProfilsContratsRoute
  '/rapports': typeof RapportsRoute
  '/rapports-financiers': typeof RapportsFinanciersRoute
  '/salaires': typeof SalairesRoute
  '/statistiques': typeof StatistiquesRoute
  '/utilisateurs': typeof UtilisateursRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/depenses'
    | '/eleves'
    | '/evaluations'
    | '/frais-scolarite'
    | '/messagerie'
    | '/notes'
    | '/paiements'
    | '/parametres'
    | '/personnel'
    | '/presences'
    | '/profil'
    | '/profils-contrats'
    | '/rapports'
    | '/rapports-financiers'
    | '/salaires'
    | '/statistiques'
    | '/utilisateurs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/depenses'
    | '/eleves'
    | '/evaluations'
    | '/frais-scolarite'
    | '/messagerie'
    | '/notes'
    | '/paiements'
    | '/parametres'
    | '/personnel'
    | '/presences'
    | '/profil'
    | '/profils-contrats'
    | '/rapports'
    | '/rapports-financiers'
    | '/salaires'
    | '/statistiques'
    | '/utilisateurs'
  id:
    | '__root__'
    | '/'
    | '/depenses'
    | '/eleves'
    | '/evaluations'
    | '/frais-scolarite'
    | '/messagerie'
    | '/notes'
    | '/paiements'
    | '/parametres'
    | '/personnel'
    | '/presences'
    | '/profil'
    | '/profils-contrats'
    | '/rapports'
    | '/rapports-financiers'
    | '/salaires'
    | '/statistiques'
    | '/utilisateurs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DepensesRoute: typeof DepensesRoute
  ElevesRoute: typeof ElevesRoute
  EvaluationsRoute: typeof EvaluationsRoute
  FraisScolariteRoute: typeof FraisScolariteRoute
  MessagerieRoute: typeof MessagerieRoute
  NotesRoute: typeof NotesRoute
  PaiementsRoute: typeof PaiementsRoute
  ParametresRoute: typeof ParametresRoute
  PersonnelRoute: typeof PersonnelRoute
  PresencesRoute: typeof PresencesRoute
  ProfilRoute: typeof ProfilRoute
  ProfilsContratsRoute: typeof ProfilsContratsRoute
  RapportsRoute: typeof RapportsRoute
  RapportsFinanciersRoute: typeof RapportsFinanciersRoute
  SalairesRoute: typeof SalairesRoute
  StatistiquesRoute: typeof StatistiquesRoute
  UtilisateursRoute: typeof UtilisateursRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/utilisateurs': {
      id: '/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof UtilisateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistiques': {
      id: '/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof StatistiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salaires': {
      id: '/salaires'
      path: '/salaires'
      fullPath: '/salaires'
      preLoaderRoute: typeof SalairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports-financiers': {
      id: '/rapports-financiers'
      path: '/rapports-financiers'
      fullPath: '/rapports-financiers'
      preLoaderRoute: typeof RapportsFinanciersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports': {
      id: '/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof RapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profils-contrats': {
      id: '/profils-contrats'
      path: '/profils-contrats'
      fullPath: '/profils-contrats'
      preLoaderRoute: typeof ProfilsContratsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presences': {
      id: '/presences'
      path: '/presences'
      fullPath: '/presences'
      preLoaderRoute: typeof PresencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personnel': {
      id: '/personnel'
      path: '/personnel'
      fullPath: '/personnel'
      preLoaderRoute: typeof PersonnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiements': {
      id: '/paiements'
      path: '/paiements'
      fullPath: '/paiements'
      preLoaderRoute: typeof PaiementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messagerie': {
      id: '/messagerie'
      path: '/messagerie'
      fullPath: '/messagerie'
      preLoaderRoute: typeof MessagerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frais-scolarite': {
      id: '/frais-scolarite'
      path: '/frais-scolarite'
      fullPath: '/frais-scolarite'
      preLoaderRoute: typeof FraisScolariteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluations': {
      id: '/evaluations'
      path: '/evaluations'
      fullPath: '/evaluations'
      preLoaderRoute: typeof EvaluationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eleves': {
      id: '/eleves'
      path: '/eleves'
      fullPath: '/eleves'
      preLoaderRoute: typeof ElevesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depenses': {
      id: '/depenses'
      path: '/depenses'
      fullPath: '/depenses'
      preLoaderRoute: typeof DepensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DepensesRoute: DepensesRoute,
  ElevesRoute: ElevesRoute,
  EvaluationsRoute: EvaluationsRoute,
  FraisScolariteRoute: FraisScolariteRoute,
  MessagerieRoute: MessagerieRoute,
  NotesRoute: NotesRoute,
  PaiementsRoute: PaiementsRoute,
  ParametresRoute: ParametresRoute,
  PersonnelRoute: PersonnelRoute,
  PresencesRoute: PresencesRoute,
  ProfilRoute: ProfilRoute,
  ProfilsContratsRoute: ProfilsContratsRoute,
  RapportsRoute: RapportsRoute,
  RapportsFinanciersRoute: RapportsFinanciersRoute,
  SalairesRoute: SalairesRoute,
  StatistiquesRoute: StatistiquesRoute,
  UtilisateursRoute: UtilisateursRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
